const Images={
    Icon_san_dau: require("themes/images/icon-pitch.png"),
    Logo: require("themes/images/logo-football.png"),
    Img_Profile: require("themes/images/img-profile.jpg"),
    On1: require("themes/images/On5.jpg"),
    On2: require("themes/images/On6.png"),
    On3: require("themes/images/On7.jpg"),
    Fb: require("themes/images/fb.png"),
    gg: require("themes/images/gg.png"),
    tw: require("themes/images/tw.png"),
    // left:require("themes/images/left-arrow.png"),
    // right:require("themes/images/right-arrow.png"),
    // BG:require("themes/images/backgroundFootball.jpg"),
    purpleBG:require("themes/images/bgPurple.jpg"),
    // whiteBG:require("themes/images/bg-white.jpg"),
    mini: require("themes/images/img-minion.png"),
    sanb: require("themes/images/sanb.jpg"),
    shoes: require("themes/images/shoes.png"),
    coca: require("themes/images/cocacola.jpg"),
    bayup: require("themes/images/sevenup.png"),
    revive: require("themes/images/reviveup.png"),
    marlboro: require("themes/images/marlboro.jpg"),
    momo: require("themes/images/momo.png"),
    card: require("themes/images/card2.jpg"),
}
export default Images;